version: '3'
services:
  db:
    image: postgres:latest
    container_name: db_postgres
    environment:
      - POSTGRES_USER=${DB_USER}  
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '${DB_PORT}:${DB_PORT}'
    networks:
      - net
  app:
    build: .
    ports: 
      - 8080:8080 
    depends_on:
      db:     
        condition: service_healthy   
    networks:
      - net

networks:
  net:
    driver: bridge